spring:
  application:
    name: springboot-init
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    # Redis 分布式登录
    # store-type: redis
    # 30 分钟
    timeout: 2592000
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: root
  # Redis 配置
  #  redis:
  #    database: 1
  #    host: localhost
  #    port: 6379
  #    timeout: 5000
  #    password: 123456
  # Elasticsearch
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # ????
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 9527
  servlet:
    context-path: /api
    # cookie 30 分钟
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 标识删除字段
      logic-delete-value: 1 # 删除 1
      logic-not-delete-value: 0 # 未删除 0
# 微信第三方登录
wx:
  # ??????
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 替换自己的
  open:
    appId: xxx
    appSecret: xxx
# 存储服务
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.abing.springbootinit.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
